return {
  { "nvie/vim-flake8", ft = { "python" } },
  { "fatih/vim-go", ft = { "go" } },
  { "pangloss/vim-javascript", ft = { "javascript", "javascriptreact" } },
  { "mxw/vim-jsx", ft = { "javascript", "javascriptreact" } },
  { "matthewsimo/angular-vim-snippets", ft = { "typescript", "typescriptreact", "angular" } },
  { "nathanaelkane/vim-indent-guides" },
  { "elzr/vim-json", ft = { "json" } },
  { "Shougo/deoplete.nvim", dependencies = { "roxma/nvim-yarp", "roxma/vim-hug-neovim-rpc" }, build = ":UpdateRemotePlugins" },
  { "deoplete-plugins/deoplete-go", build = "make", ft = { "go" } },
  { "tenfyzhong/CompleteParameter.vim" },
  { "carakan/deoplete-emoji" },
  { "Shougo/neosnippet" },
  { "Shougo/neosnippet-snippets" },
  { "majutsushi/tagbar" },
  { "airblade/vim-gitgutter" },
  { "scrooloose/syntastic" },
  { "godlygeek/tabular" },
  { "plasticboy/vim-markdown", ft = { "markdown" } },
  { "cespare/vim-toml", ft = { "toml" } },
  { "maksimr/vim-jsbeautify", ft = { "javascript", "json" } },
  { "scrooloose/nerdtree" },
  { "Xuyuanp/nerdtree-git-plugin" },
  { "morhetz/gruvbox" },
  { "luochen1990/rainbow" },
  { "RRethy/vim-illuminate" },
  { "towolf/vim-helm", ft = { "yaml", "helm" } },
  { "wakatime/vim-wakatime" },
  { "imain/notmuch-vim" },
  { "itchyny/calendar.vim" },
  { "google/vim-jsonnet", ft = { "jsonnet" } },
  { "tpope/vim-unimpaired" },
  { "catppuccin/vim", name = "catppuccin" },
  { "hashivim/vim-terraform", ft = { "terraform" } },
  { "juliosueiras/vim-terraform-completion", ft = { "terraform" } },
}
